Repository wecode-bootcamp-korea/13-Winted-frontend, pull requests merged in 2020-11, with the labels that each got.

#6 [13기 이예린] Add : Job Component
  src/Components/Job/Job.js
  src/config.js
Labels: Status: 수정 요청

#3 [13기 김한나] Nav 컴포넌트 리뷰반영 완료
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavDropdown.js
  src/Components/Nav/NavDropdown.scss
  src/Components/Nav/Navdata.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 진행중

#8 [13기 김한나] Nav 컴포넌트 기능추가 리뷰요청
  .eslintrc.json
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavDropdown.js
  src/Components/Nav/NavDropdown.scss
Labels: Status: 리뷰 진행중

#2 [13기 민지연] 리뷰반영 완료
  package-lock.json
  package.json
  public/data/data.json
  public/index.html
  src/Pages/Recommend/RecommendComponent/Recommend.js
  src/Pages/Recommend/RecommendComponent/Recommend.scss
  src/Pages/Recommend/RecommendComponent/RecommendBox.js
  src/Pages/Recommend/RecommendComponent/RecommendList.js
  src/Pages/Recommend/RecommendComponent/RecommendListBox.js
  src/Pages/Recommend/RecommendComponent/RecommendListModal.js
  src/Pages/Recommend/RecommendComponent/RecommendModal.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTap.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTap.scss
  src/Pages/Recommend/RecommendComponent/RecommendModalTapComponent/RecommendModalFirst.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTapComponent/RecommendModalFourth.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTapComponent/RecommendModalSecond.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTapComponent/RecommendModalThird.js
  src/Pages/Recommend/RecommendComponent/RecommendRequest.js
  src/Pages/Recommend/RecommendComponent/RecommendUserBox.js
  src/Pages/Recommend/RecommendComponent/RecommendUserModal.js
  src/Pages/Recommend/RecommendComponent/RecommendVehicles.js
  src/Pages/Recommend/RecommendTap.js
  src/Pages/Recommend/RecommendTap.scss
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청

#4 [Winted 이예린] joblist Page
  .prettierrc.json
  package-lock.json
  package.json
  public/data/category_list.json
  public/data/fiteringTags_list.json
  public/data/job_list.json
  public/data/nav.png
  public/data/userFilter_data.json
  src/Components/Job/Job.js
  src/Pages/Joblist/Components/CategoryNav/CategoryNav.js
  src/Pages/Joblist/Components/CategoryNav/CategoryRoute/CategoryRoute.js
  src/Pages/Joblist/Components/CategoryNav/CategorySlider/CategoryButton.js
  src/Pages/Joblist/Components/CategoryNav/CategorySlider/CategorySlider.js
  src/Pages/Joblist/Components/JoblistMain/CareerModal.js
  src/Pages/Joblist/Components/JoblistMain/JoblistMain.js
  src/Pages/Joblist/Components/JoblistMain/LocationModal.js
  src/Pages/Joblist/Components/JoblistMain/TagModal.js
  src/Pages/Joblist/Joblist.js
  src/Routes.js
  src/config.js
  src/index.js
  src/store/actions/index.js
  src/store/reducers/index.js
  src/store/reducers/userFilterReducer.js
Labels: Status: 리뷰 요청

#9 [13기 김한나] DetailPage 컴포넌트 리뷰요청
  package-lock.json
  package.json
  src/Pages/Login/DetailPage/DetailData.js
  src/Pages/Login/DetailPage/DetailPage.js
  src/Pages/Login/DetailPage/DetailSlider/DetailSlider.js
  src/Pages/Login/DetailPage/DetailSlider/DetailSlider.scss
  src/Pages/Login/DetailPage/Map/MapContent.js
  src/Pages/Login/DetailPage/Map/MapContent.scss
  src/Pages/Login/DetailPage/Map/test.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#5 [13기 김수연] 회원가입/로그인/소셜로그인/연봉차트/Footer
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  public/data/job-category.json
  public/data/salary.json
  public/data/years-of-service.json
  public/images/footer-logo.JPG
  public/images/kakao_login_large_wide.png
  public/images/logo.png
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/LogIn/LogIn.js
  src/Pages/LogIn/components/SignIn/KakaoButton.js
  src/Pages/LogIn/components/SignIn/SignInEmail.js
  src/Pages/LogIn/components/SignIn/SignInPw.js
  src/Pages/LogIn/components/SignUp/SignUp.js
  src/Pages/Login/Login.scss
  src/Pages/Salary/Salary.js
  src/Pages/Salary/components/Banner.js
  src/Pages/Salary/components/Chart.js
  src/Pages/Salary/components/UpgradePosition.js
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#10 [13기 민지연] FIX : conflict 해결
  src/Pages/Recommend/RecommendComponent/RecommendList.js
  src/Pages/Recommend/RecommendComponent/RecommendListBox.js
  src/Pages/Recommend/RecommendComponent/RecommendListModal.js
  src/Pages/Recommend/RecommendComponent/RecommendListModalComponent/RecommendListModalEdit.js
  src/Pages/Recommend/RecommendComponent/RecommendListModalComponent/RecommendListModalText.js
  src/Pages/Recommend/RecommendComponent/RecommendModal.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTap.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTapComponent/RecommendModalFirst.js
  src/Pages/Recommend/RecommendComponent/RecommendRequest.js
  src/Pages/Recommend/RecommendComponent/RecommendUserModal.js
Labels: Status: 리뷰 요청

#11 [13기 김한나] DetailPage 컴포넌트 기능추가 구현 리뷰요청
  src/Pages/Login/DetailPage/DetailPage.js
Labels: Status: 리뷰 요청

#12 [13기 김수연] Nav, 로그인/회원가입 버그 수정
  src/Components/Nav/Nav.js
  src/Pages/LogIn/LogIn.js
  src/Pages/LogIn/components/SignIn/KakaoButton.js
  src/Pages/LogIn/components/SignIn/SignInEmail.js
  src/Pages/LogIn/components/SignIn/SignInPw.js
  src/Pages/LogIn/components/SignUp/SignUp.js
  src/Pages/Salary/components/UpgradePosition.js
  src/config.js
Labels: Status: 리뷰 요청

#7 [Winted 이예린] 이력서 리스트 페이지
  public/data/resume_detail.json
  public/data/resume_list.json
  src/Pages/Login/Login.scss
  src/Pages/Recommend/RecommendComponent/RecommendModalTap.js
  src/Pages/Recommend/RecommendTap.js
  src/Pages/Resumelist/DetailBox.js
  src/Pages/Resumelist/Resume.js
  src/Pages/Resumelist/ResumeDetail.js
  src/Pages/Resumelist/Resumelist.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#13 [winted 이예린] Joblist 버그수정
  src/Components/Job/Job.js
  src/Components/Nav/NavDropdown.js
  src/Pages/Favoritelist/Favoritelist.js
  src/Pages/Joblist/Components/CategoryNav/CategoryNav.js
  src/Pages/Joblist/Components/CategoryNav/CategoryRoute/CategoryRoute.js
  src/Pages/Joblist/Components/CategoryNav/CategorySlider/CategoryButton.js
  src/Pages/Joblist/Components/CategoryNav/CategorySlider/CategorySlider.js
  src/Pages/Joblist/Components/JoblistMain/JoblistMain.js
  src/Pages/Joblist/Components/JoblistMain/TagModal.js
  src/Pages/Joblist/Joblist.js
  src/Routes.js
  src/config.js
  src/store/actions/index.js
  src/store/reducers/index.js
  src/store/reducers/jobFetchReducer.js
  src/store/reducers/urlUpdateReducer.js
Labels: Status: 리뷰 요청

#14 [13기 김수연] Detail page bug 수정
  src/Pages/LogIn/components/SignIn/SignInEmail.js
  src/Pages/LogIn/components/SignIn/SignInPw.js
  src/Pages/LogIn/components/SignUp/SignUp.js
  src/Pages/Login/DetailPage/DetailPage.js
  src/Pages/Login/DetailPage/Map/MapContent.js
  src/Pages/Recommend/RecommendComponent/RecommendList.js
  src/Pages/Recommend/RecommendComponent/RecommendListModal.js
  src/Pages/Recommend/RecommendComponent/RecommendModalTapComponent/RecommendModalFirst.js
  src/Pages/Salary/components/UpgradePosition.js
Labels: Status: 리뷰 요청
